"""Capture the finished English mobile product with fictional family information."""
import json,html,shutil
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
from browser_support import chromium_executable

OUT=Path('output/mobile-product-review');OUT.mkdir(parents=True,exist_ok=True)
screens=[];errors=[]
def capture(page,slug,title):
    page.evaluate('document.fonts.ready');page.evaluate('scrollTo(0,0)')
    page.screenshot(path=str(OUT/(slug+'.png')),animations='disabled')
    screens.append({'title':title,'file':slug+'.png'})
def go(page,step):
    if page.url.endswith('#section-'+str(step)):return
    if page.locator('#m-navigator').is_hidden():page.locator('#m-back').click()
    page.locator('#m-navigator').click();page.locator(f'[data-target="{step}"]').click()
    expect(page.locator('#m-sheet')).not_to_be_visible()

with sync_playwright() as p:
    b=p.chromium.launch(executable_path=chromium_executable(),headless=True,chromium_sandbox=True)
    c=b.new_context(viewport={'width':390,'height':844},has_touch=True,is_mobile=True,reduced_motion='reduce',accept_downloads=True)
    c.add_init_script("Object.defineProperty(navigator,'canShare',{value:undefined,configurable:true})")
    page=c.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
    page.goto('http://127.0.0.1:5050/')
    capture(page,'00-landing','Landing · preserved hero')
    page.locator('.hero .button.primary').first.click()
    expect(page.locator('.m-heading h1')).to_have_text('Let’s make your biodata.')
    page.locator('[data-for="daughter"]').click();capture(page,'01-start','Start · creating for a daughter')
    page.locator('#m-primary-action').click();capture(page,'02-basics-empty','Personal details · empty')
    for key,value in {'name':'Ananya Sharma','age':'28','height':'165','city':'Jaipur'}.items():page.locator(f'[data-field="personal.0.{key}"]').fill(value)
    capture(page,'03-basics','Personal details · filled')
    page.locator('[data-m="add-details"]').click();capture(page,'04-add-detail','Add an optional detail')
    page.locator('[data-m="close-sheet"]').click();expect(page.locator('#m-sheet')).not_to_be_visible()
    page.locator('#m-primary-action').click();capture(page,'05-education-empty','Education and work · empty')
    page.locator('[data-m="entry-add"][data-section="education"]').click()
    page.locator('[data-field="education.0.degree"]').fill('M.Arch, Sustainable Design')
    page.locator('[data-field="education.0.institution"]').fill('CEPT University, Ahmedabad')
    page.locator('[data-field="education.0.year"]').fill('2021')
    capture(page,'06-education-editor','Education · focused entry editor')
    page.locator('#m-primary-action').click()
    page.locator('[data-m="entry-add"][data-section="career"]').click()
    page.locator('[data-field="career.0.role"]').fill('Architect')
    page.locator('[data-field="career.0.company"]').fill('Independent design studio')
    page.locator('[data-field="career.0.location"]').fill('Jaipur')
    page.locator('#m-primary-action').click();capture(page,'07-education-work','Education and work · summary cards')
    page.locator('#m-primary-action').click();capture(page,'08-family-empty','Family · empty')
    for key,value in [('father','Rajesh Sharma · Teacher'),('mother','Poonam Sharma · Homemaker'),('siblings','One younger brother, studying engineering')]:
        page.locator(f'[data-key="{key}"]').first.click();page.locator('#m-family-text').fill(value)
        if key=='father':capture(page,'09-family-editor','Family · focused editor')
        page.locator('#m-primary-action').click()
    capture(page,'10-family','Family · summary cards')
    page.locator('#m-primary-action').click()
    page.get_by_label('Your introduction',exact=True).fill('I am an architect who enjoys thoughtful design, good books and discovering new places. Family and close friendships keep me grounded. I would love to build a life filled with kindness, curiosity and shared adventures.')
    for hobby in ['reading','travel','music']:page.locator(f'[data-hobby="{hobby}"]').click()
    capture(page,'11-about','About you · writing and interests')
    page.locator('#step-content [data-m="custom-add"]').click()
    page.locator('[data-custom-title]').fill('A little more about me')
    page.locator('[data-custom$=":0:label"]').fill('My favourite weekend')
    page.locator('[data-custom$=":0:value"]').fill('A morning walk, a home-cooked lunch and an evening with family.')
    capture(page,'12-custom','Custom section · focused editor')
    page.locator('#m-primary-action').click();page.locator('#m-primary-action').click()
    capture(page,'13-optional-empty','Culture and birth · optional')
    page.locator('[data-section="astrology"][data-m="add-details"]').click();capture(page,'14-birth-options','Birth details · add only what matters')
    page.locator('[data-m="close-sheet"]').click();expect(page.locator('#m-sheet')).not_to_be_visible()
    page.locator('[data-m="skip"]').click();capture(page,'15-photos-empty','Photos · empty')
    page.locator('#photo-input').set_input_files('app/static/artwork/demo-portrait-female.jpg')
    expect(page.locator('#crop-dialog')).to_be_visible();capture(page,'16-crop','Full-screen photo editor')
    page.locator('#apply-crop').click();expect(page.locator('#crop-dialog')).not_to_be_visible()
    capture(page,'17-photo','Photos · main portrait')
    page.locator('[data-m="photo-options"]').click();capture(page,'18-photo-options','Photo options')
    page.locator('[data-m="close-sheet"]').click();expect(page.locator('#m-sheet')).not_to_be_visible()
    page.locator('#m-primary-action').click()
    expect(page.locator('#document-preview')).to_have_attribute('data-state','ready',timeout=65000)
    capture(page,'19-design','Choose a design · horizontal gallery')
    page.locator('#m-navigator').click();capture(page,'20-navigator','Section navigator')
    page.locator('[data-m="close-sheet"]').click();expect(page.locator('#m-sheet')).not_to_be_visible()
    page.locator('#m-preview-action').click();capture(page,'21-preview','Full-screen biodata preview')
    page.locator('[data-m="preview-continue"]').click();expect(page.locator('#m-review-image')).to_be_visible()
    capture(page,'22-review','Review your biodata')
    page.locator('[data-m="visibility"]').click();page.locator('.m-inclusion summary').first.click()
    capture(page,'23-inclusion','Choose what appears in the file')
    page.locator('[data-m="close-sheet"]').last.click();expect(page.locator('#m-sheet')).not_to_be_visible()
    page.locator('#m-primary-action').click();page.locator('#m-export-consent').check();capture(page,'24-download','Choose a download format')
    with page.expect_download(timeout=65000) as dl:page.locator('[data-format="pdf"]').click()
    expect(page.locator('.m-complete')).to_be_visible();capture(page,'25-success','Download complete')
    page.locator('#share-file').click();capture(page,'26-share','Share help · when native sharing is unavailable')
    page.locator('[data-m="close-sheet"]').last.click();expect(page.locator('#m-sheet')).not_to_be_visible()
    page.locator('#m-options').click();capture(page,'27-draft','Draft options')
    page.locator('[data-m="privacy"]').click();capture(page,'28-privacy','Privacy · while creating and sharing')
    page.go_back();expect(page.locator('#m-sheet')).not_to_be_visible()
    page.locator('#m-options').click();page.locator('[data-m="delete"]').click();capture(page,'29-delete','Delete confirmation')
    page.locator('#confirm-cancel').click();expect(page.locator('#info-dialog')).not_to_be_visible()
    # Final negative-state check: a profile with every section omitted cannot create an empty file.
    page.locator('[data-m="edit-again"]').click();page.locator('[data-target="10"]').click()
    page.locator('[data-m="visibility"]').click()
    for control in page.locator('[data-m-section]').all():
        if control.locator('xpath=ancestor::details').count():control.locator('xpath=ancestor::details').evaluate('(e)=>e.open=true')
        if control.is_checked():control.uncheck()
    page.locator('[data-m="close-sheet"]').last.click();expect(page.locator('#m-sheet')).not_to_be_visible()
    expect(page.locator('#m-primary-action')).to_be_disabled()
    expect(page.locator('.m-heading')).to_contain_text('Include at least one detail')
    assert not errors,errors
    c.close();b.close()

for filename,title in [('recovery-save-error.png','Save failure · retry or back up'),('recovery-preview-error.png','Preview failure · retry'),('recovery-export-error.png','Download failure · retry')]:
    shutil.copy(Path('tmp/qa/mobile-redesign')/filename,OUT/filename);screens.append({'title':title,'file':filename})
(OUT/'manifest.json').write_text(json.dumps({'viewport':'390 × 844','screens':screens,'browserErrors':errors,'data':'Fictional sample data. Original user drafts untouched.'},indent=2))
cards=''.join(f'<article><h2>{i+1:02d} · {html.escape(s["title"])}</h2><a href="{s["file"]}" target="_blank"><img loading="lazy" src="{s["file"]}" alt="{html.escape(s["title"])}"></a></article>' for i,s in enumerate(screens))
(OUT/'index.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Parichay · Redesigned mobile experience</title><style>*{box-sizing:border-box}body{margin:0;background:#f3ece7;color:#372731;font:16px/1.5 system-ui,sans-serif}header{padding:44px max(24px,5vw);background:#fffcf8;border-bottom:1px solid #d6c8cc}h1{font:42px/1.1 Georgia,serif;color:#602941;margin:12px 0}header p{max-width:760px;color:#6d5964}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:24px;padding:32px max(24px,5vw)}article{background:#fff;border:1px solid #d9c9cf;border-radius:12px;overflow:hidden}h2{font-size:15px;font-weight:600;min-height:78px;margin:0;padding:18px}a{display:block;border-top:1px solid #e5d9df}img{display:block;width:100%;height:auto}a:focus-visible{outline:3px solid #6a2945;outline-offset:-4px}@media(min-width:1600px){main{grid-template-columns:repeat(5,1fr)}}</style><header><small>PARICHAY · MOBILE PRODUCT REVIEW</small><h1>A calmer way to create.</h1><p>33 screens and states from the redesigned mobile product. English · 390 × 844 · fictional information. Tap a screenshot to open it at full size.</p><p>These are unaltered viewport captures from the running app. Longer pages scroll. File pickers, the physical keyboard and native system share sheets are outside the browser captures.</p></header><main>'''+cards+'</main></html>')
print(f'Captured {len(screens)} mobile screens/states; parent flow and empty-export guard passed.')
