"""End-to-end browser checks for the separate mobile presentation."""
import json,base64,re
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
from browser_support import chromium_executable
OUT=Path('tmp/qa/mobile-redesign');OUT.mkdir(parents=True,exist_ok=True)
ROOT=Path(__file__).resolve().parents[1]
errors=[];events=[]
READ="""async()=>{const {openDraftStore}=await import('/static/js/storage.js');return await (await openDraftStore()).get();}"""
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=chromium_executable(),headless=True,chromium_sandbox=True)
 context=b.new_context(viewport={'width':390,'height':844},is_mobile=True,has_touch=True,accept_downloads=True)
 context.add_init_script("window.reviewEvents=[];document.addEventListener('parichay:analytics',e=>window.reviewEvents.push(e.detail));Object.defineProperty(navigator,'canShare',{value:undefined,configurable:true});")
 page=context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:5050/create')
 expect(page.locator('.m-heading h1')).to_be_visible()
 assert page.locator('#section-jump').is_hidden()
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-start.png'),full_page=True)
 page.locator('#m-primary-action').click()
 expect(page.locator('[data-field="personal.0.name"]')).to_be_visible()
 page.locator('[data-field="personal.0.name"]').fill('Kavya UX Sample')
 page.locator('[data-field="personal.0.age"]').fill('29')
 page.locator('[data-field="personal.0.height"]').fill('173')
 page.locator('[data-field="personal.0.city"]').fill('Pune')
 page.locator('[data-m="unit"][data-unit="ft"]').click()
 expect(page.locator('#m-feet')).to_have_value('5');expect(page.locator('#m-inches')).to_have_value('8')
 page.locator('[data-m="unit"][data-unit="cm"]').click()
 expect(page.locator('[data-field="personal.0.height"]')).to_have_value('173')
 page.locator('[data-m="add-details"]').click();expect(page.locator('#m-sheet')).to_be_visible()
 page.locator('[data-m="add-field"][data-id="contact.0.phone"]').click()
 expect(page.locator('#m-sheet')).not_to_be_visible()
 page.locator('[data-field="contact.0.phone"]').fill('9999999999')
 page.wait_for_timeout(500);page.reload()
 expect(page.locator('[data-field="contact.0.phone"]')).to_have_value('9999999999')
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-basics.png'),full_page=True)
 page.locator('#m-primary-action').click()
 expect(page.locator('[data-m="entry-add"][data-section="education"]')).to_be_visible()
 page.locator('[data-m="entry-add"][data-section="education"]').click()
 page.locator('[data-field="education.0.degree"]').fill('M.Des, Interaction Design')
 page.locator('[data-field="education.0.institution"]').fill('IIT Guwahati')
 page.locator('[data-field="education.0.year"]').fill('2020')
 page.locator('#m-primary-action').click()
 expect(page.locator('.m-record')).to_have_count(1)
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-life.png'),full_page=True)
 page.locator('#m-primary-action').click()
 page.locator('[data-m="family-edit"][data-key="father"]').click()
 page.locator('#m-family-text').fill('Rajesh Mehta · Architect')
 page.locator('#m-primary-action').click()
 expect(page.locator('.m-record')).to_contain_text('Rajesh Mehta')
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-family.png'),full_page=True)
 page.locator('#m-primary-action').click()
 page.locator('[data-field="about.0.introduction"]').fill('I enjoy design, reading and weekends with family.')
 for hobby in ['reading','travel','music','cooking','fitness']:page.locator(f'[data-hobby="{hobby}"]').click()
 expect(page.locator('#hobby-count')).to_have_text('5 / 5')
 page.locator('[data-m="custom-add"]').click()
 page.locator('[data-custom-title]').fill('A little more about me')
 page.locator('[data-custom$=":0:label"]').fill('Weekends')
 page.locator('[data-custom$=":0:value"]').fill('Long walks and cooking with family.')
 page.locator('#m-primary-action').click()
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-about.png'),full_page=True)
 page.locator('#m-primary-action').click()
 assert page.locator('[data-field]').count()==0
 page.locator('[data-m="add-details"][data-section="culture"]').click()
 page.locator('[data-m="add-field"][data-id="culture.0.community"]').click()
 page.locator('[data-field="culture.0.community"]').fill('Sample community')
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-culture.png'),full_page=True)
 page.locator('#m-primary-action').click()
 page.locator('#photo-input').set_input_files(str(ROOT/'app/static/artwork/demo-portrait-female.jpg'))
 expect(page.locator('#crop-dialog')).to_be_visible()
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-crop.png'))
 page.locator('#apply-crop').click()
 expect(page.locator('#crop-dialog')).not_to_be_visible();expect(page.locator('.m-photo-main img')).to_be_visible()
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-photos.png'),full_page=True)
 page.locator('#m-primary-action').click()
 expect(page.locator('.design-card')).to_have_count(page.locator('#app-config').evaluate('(el)=>JSON.parse(el.textContent).templates.length'))
 assert page.locator('.design-card').first.bounding_box()['width']>260
 page.locator('[data-template="professional"]').click()
 expect(page.locator('#document-preview')).to_have_attribute('data-state','ready',timeout=65000)
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-design.png'),full_page=True)
 page.locator('#m-preview-action').click();expect(page.locator('#preview-dialog')).to_be_visible()
 assert page.locator('#preview-dialog').bounding_box()['width']==390
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-preview.png'))
 page.go_back();expect(page.locator('#preview-dialog')).not_to_be_visible()
 page.locator('#m-primary-action').click()
 expect(page.locator('#m-review-image')).to_be_visible(timeout=65000)
 page.locator('[data-m="visibility"]').click()
 page.locator('.m-inclusion').filter(has_text='Get in touch').locator('summary').click()
 page.locator('[data-m-inclusion="contact.0.phone"]').uncheck()
 page.locator('[data-m="close-sheet"]').last.click()
 expect(page.locator('#m-sheet')).not_to_be_visible()
 expect(page.locator('#preview-text')).not_to_contain_text('9999999999',timeout=65000)
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-review.png'),full_page=True)
 page.locator('#m-primary-action').click()
 page.locator('#m-export-consent').check()
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-format-sheet.png'))
 with page.expect_download(timeout=65000) as dl:page.locator('[data-format="pdf"]').click()
 dl.value.save_as(OUT/'mobile-flow.pdf')
 expect(page.locator('.m-complete')).to_be_visible()
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-success.png'),full_page=True)
 page.locator('#share-file').click();expect(page.locator('#m-sheet')).to_contain_text('Share on WhatsApp')
 page.evaluate('window.scrollTo(0,0)');page.screenshot(animations='disabled',path=str(OUT/'after-share.png'))
 page.go_back();expect(page.locator('#m-sheet')).not_to_be_visible()
 events=page.evaluate('window.reviewEvents')
 assert all(set(event)<= {'event','surface','section','template'} for event in events)
 assert not errors,errors
 (OUT/'journey-result.json').write_text(json.dumps({'events':events,'errors':errors,'heightConversion':True,'refresh':True,'pdfBytes':(OUT/'mobile-flow.pdf').stat().st_size},indent=2))
 context.close();b.close()
print('Mobile creation → full preview → privacy selection → actual PDF → share fallback passed.')
